apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: usepvc
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /testvolume
      name: vol
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: mypvc
